# Generated by Django 3.0.3 on 2020-02-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Short Description')),
                ('picture_url', models.CharField(blank=True, max_length=300, verbose_name='Picture URL')),
            ],
        ),
    ]
