# Generated by Django 3.0.3 on 2020-02-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Short Description')),
                ('picture_url', models.CharField(blank=True, max_length=300, verbose_name='Picture URL')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Body')),
                ('is_dayquote', models.BooleanField(default=False)),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Author')),
            ],
        ),
    ]
